import numpy as np

from algorithm.standard_nmf import standard_nmf
from algorithm.robust_l1_nmf import robust_l1_nmf


# Load one noisy dataset generated by Vaibhavi
V = np.load(
    "outputs/arrays/ORL_noisy_b10_k1.npy"
)

print("Input shape:", V.shape)


# Run standard NMF
W1, H1, losses1 = standard_nmf(
    V,
    rank=10,
    max_iter=100
)

print("\nStandard NMF")
print("W:", W1.shape)
print("H:", H1.shape)
print("Loss:", losses1[0], "->", losses1[-1])


# Run robust L1 NMF
W2, H2, losses2 = robust_l1_nmf(
    V,
    rank=10,
    max_iter=100
)

print("\nRobust L1 NMF")
print("W:", W2.shape)
print("H:", H2.shape)
print("Loss:", losses2[0], "->", losses2[-1])